# Generated by Django 5.0.6 on 2024-07-29 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_service_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelTable(
            name='service',
            table='services',
        ),
    ]
