# Generated by Django 5.0.6 on 2024-08-02 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csc_center', '0030_rename_show_working_time_csccenter_show_opening_hours'),
        ('services', '0005_alter_service_options_alter_service_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_name', models.CharField(max_length=150)),
                ('applicant_email', models.EmailField(max_length=254)),
                ('applicant_phone', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('slug', models.SlugField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('csc_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csc_center.csccenter')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.service')),
            ],
            options={
                'db_table': 'service_enquiry',
                'ordering': ['-created'],
            },
        ),
    ]
