# Generated by Django 5.0.6 on 2024-08-24 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_alter_serviceenquiry_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceenquiry',
            name='is_viewed',
            field=models.BooleanField(default=False),
        ),
    ]
