# Generated by Django 5.0.6 on 2024-05-25 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Districts',
            new_name='District',
        ),
    ]
