# Generated by Django 5.0.6 on 2024-05-27 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_districts_district'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csc_id', models.CharField(max_length=50)),
                ('service', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='CommonServiceCenter',
            fields=[
                ('csc_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=15)),
                ('alternative_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('service', models.ManyToManyField(to='home.service')),
            ],
        ),
    ]
