# Generated by Django 5.0.6 on 2024-05-27 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_commonservicecenter_csc_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonservicecenter',
            name='block',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.block'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commonservicecenter',
            name='district',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.district'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commonservicecenter',
            name='state',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.state'),
            preserve_default=False,
        ),
    ]
