# Generated by Django 5.0.6 on 2024-05-28 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_service_created_service_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonservicecenter',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
