# Generated by Django 5.0.6 on 2024-12-21 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_banners_homepagebanner'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Banners',
            new_name='Banner',
        ),
    ]
