# Generated by Django 5.0.6 on 2024-12-21 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_rename_banners_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagebanner',
            name='name',
            field=models.CharField(default='Home Page Banners', max_length=50),
        ),
    ]
