# Generated by Django 5.0.6 on 2024-12-21 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_homepagebanner_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommonServiceCenter',
        ),
    ]
