# Generated by Django 5.0.6 on 2024-12-21 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_delete_commonservicecenter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='block',
            name='state',
        ),
        migrations.RemoveField(
            model_name='district',
            name='state',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.DeleteModel(
            name='Block',
        ),
        migrations.DeleteModel(
            name='District',
        ),
        migrations.DeleteModel(
            name='State',
        ),
    ]
