# Generated by Django 5.0.6 on 2024-09-04 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('csc_center', '0035_csccenter_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CscCenterAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rejection_reason', models.TextField()),
                ('feedback', models.TextField()),
                ('slug', models.SlugField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('csc_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csc_center.csccenter')),
            ],
            options={
                'db_table': 'csc_center_action',
                'ordering': ['-updated'],
            },
        ),
    ]
