# Generated by Django 5.0.6 on 2024-09-25 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csc_admin', '0001_initial'),
        ('csc_center', '0039_rename_csc_center_id_banner_csc_center'),
        ('services', '0010_alter_serviceenquiry_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_name', models.CharField(max_length=150)),
                ('applicant_email', models.EmailField(max_length=254)),
                ('applicant_phone', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('slug', models.SlugField(blank=True, max_length=150, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('csc_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_service_enquiry_csc_center', to='csc_center.csccenter')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_service_enquiry_service', to='services.service')),
            ],
            options={
                'db_table': 'admin_service_enquiry',
                'ordering': ['-created'],
            },
        ),
    ]
