# Generated by Django 5.0.6 on 2024-09-25 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csc_admin', '0005_productenquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='productenquiry',
            name='location',
            field=models.TextField(default='Melmuri, Malappuram, Malappuram Dist, Kerala'),
            preserve_default=False,
        ),
    ]
