# Generated by Django 5.0.6 on 2024-10-26 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csc_admin', '0006_productenquiry_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csccenteraction',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='csccenteraction',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
