# Generated by Django 5.0.6 on 2024-10-26 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csc_admin', '0007_alter_csccenteraction_feedback_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csccenteraction',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True),
        ),
    ]
