# Generated by Django 5.0.6 on 2024-07-10 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csc_center', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CscCenterType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
