# Generated by Django 5.0.6 on 2024-07-10 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csc_center', '0008_csccenter_banner_csccenter_block_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='csccenter',
            table='csc_center',
        ),
    ]
