# Generated by Django 5.0.6 on 2024-07-10 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csc_center', '0009_alter_csccenter_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='district',
            table='districts',
        ),
    ]
