# Generated by Django 5.0.6 on 2024-07-11 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csc_center', '0010_alter_district_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='block',
            table='blocks',
        ),
    ]
