# Generated by Django 5.0.6 on 2024-07-17 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csc_center', '0012_alter_block_district'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='csccenter',
            name='keywords',
        ),
        migrations.DeleteModel(
            name='CscKeywords',
        ),
    ]
