# Generated by Django 5.0.6 on 2024-07-17 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csc_center', '0017_csckeywords_keyword_csckeywords_slug_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='csckeywords',
            options={'ordering': ['keyword']},
        ),
    ]
