# Generated by Django 5.0.6 on 2024-07-17 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csc_center', '0018_alter_csckeywords_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CscKeywords',
            new_name='CscKeyword',
        ),
    ]
