# Generated by Django 5.0.6 on 2024-07-22 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csc_center', '0020_cscnametype_alter_csccenter_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='csccenter',
            old_name='location_latitude',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='csccenter',
            old_name='location_longitude',
            new_name='longitude',
        ),
    ]
