# Generated by Django 5.0.6 on 2024-07-23 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csc_center', '0021_rename_location_latitude_csccenter_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='csccenter',
            name='slug',
            field=models.SlugField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='csccenter',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
