# Generated by Django 5.0.6 on 2024-07-23 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csc_center', '0022_csccenter_slug_alter_csccenter_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='rough/')),
            ],
        ),
    ]
