# Generated by Django 5.0.6 on 2024-07-23 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csc_center', '0024_image_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='rough_banner/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='rough/'),
        ),
    ]
