# Generated by Django 5.0.6 on 2024-07-23 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csc_center', '0025_alter_image_banner_alter_image_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='name',
            field=models.CharField(default='No Image', max_length=150),
        ),
    ]
