# Generated by Django 5.0.6 on 2024-07-25 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csc_center', '0027_csccenter_created_csccenter_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csccenter',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
