# Generated by Django 5.0.6 on 2024-07-26 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csc_center', '0028_alter_csccenter_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='csccenter',
            name='show_social_media_links',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='csccenter',
            name='show_working_time',
            field=models.BooleanField(default=True),
        ),
    ]
