# Generated by Django 5.0.6 on 2024-08-26 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csc_center', '0031_csccenter_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='csccenter',
            name='qr_code_image',
            field=models.ImageField(blank=True, null=True, upload_to='csc_qr_codes/'),
        ),
    ]
