# Generated by Django 5.0.6 on 2024-09-02 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csc_center', '0032_csccenter_qr_code_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='csccenter',
            options={'ordering': ['name']},
        ),
    ]
