# Generated by Django 5.0.6 on 2024-09-03 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csc_center', '0033_alter_csccenter_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='csccenter',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
