# Generated by Django 5.0.6 on 2024-09-04 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csc_center', '0034_csccenter_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='csccenter',
            name='status',
            field=models.CharField(default='Not Viewed', max_length=100),
        ),
    ]
