# Generated by Django 5.0.6 on 2024-09-09 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csc_center', '0037_banner_delete_banners'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='csccenter',
            name='banner',
        ),
        migrations.AddField(
            model_name='csccenter',
            name='banners',
            field=models.ManyToManyField(to='csc_center.banner'),
        ),
    ]
