# Generated by Django 5.0.6 on 2024-10-01 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csc_center', '0039_rename_csc_center_id_banner_csc_center'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csccenter',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='csc_center.cscnametype'),
        ),
    ]
