# Generated by Django 5.0.6 on 2024-10-01 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csc_center', '0040_alter_csccenter_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csccenter',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
