# Generated by Django 5.0.6 on 2024-10-01 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csc_center', '0041_alter_csccenter_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csccenter',
            name='slug',
            field=models.SlugField(blank=True, max_length=500, null=True, unique=True),
        ),
    ]
