# Generated by Django 5.0.6 on 2024-10-01 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csc_center', '0045_alter_csccenter_latitude_alter_csccenter_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csccenter',
            name='latitude',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='csccenter',
            name='longitude',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
