# Generated by Django 5.0.6 on 2024-10-01 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csc_center', '0046_alter_csccenter_latitude_alter_csccenter_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csccenter',
            name='street',
            field=models.CharField(max_length=250),
        ),
    ]
