# Generated by Django 5.0.6 on 2024-10-02 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csc_center', '0048_alter_csccenter_street'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csccenter',
            name='whatsapp_number',
            field=models.CharField(max_length=100),
        ),
    ]
