# Generated by Django 5.0.6 on 2024-10-04 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csc_center', '0049_alter_csccenter_whatsapp_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='block',
            options={'ordering': ['block']},
        ),
        migrations.AlterModelOptions(
            name='district',
            options={'ordering': ['district']},
        ),
        migrations.AlterModelOptions(
            name='state',
            options={'ordering': ['state']},
        ),
        migrations.AlterField(
            model_name='csccenter',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
