# Generated by Django 5.0.6 on 2024-10-05 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csc_center', '0050_alter_block_options_alter_district_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csccenter',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
