# Generated by Django 5.0.6 on 2024-10-07 10:03

import csc_center.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csc_center', '0053_alter_csccenter_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csccenter',
            name='id',
            field=models.CharField(default=csc_center.models.csc_id_generator, max_length=50, primary_key=True, serialize=False),
        ),
    ]
