# Generated by Django 5.0.6 on 2024-10-14 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csc_center', '0054_alter_csccenter_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='district',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='state',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
