# Generated by Django 5.0.6 on 2024-10-17 17:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csc_center', '0055_block_slug_district_slug_state_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='csckeyword',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 10, 17, 17, 30, 31, 800372)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='csckeyword',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
