# Generated by Django 5.0.6 on 2024-11-26 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csc_center', '0058_alter_csccenter_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='csccenter',
            name='payment_assigned_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
