# Generated by Django 5.0.6 on 2024-11-26 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csc_center', '0059_csccenter_payment_assigned_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='csccenter',
            old_name='payment_assigned_date',
            new_name='payment_implemented_date',
        ),
    ]
