# Generated by Django 5.0.6 on 2024-11-26 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csc_center', '0060_rename_payment_assigned_date_csccenter_payment_implemented_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='csccenter',
            name='inactive_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
