# Generated by Django 5.0.6 on 2024-11-28 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csc_center', '0062_remove_csccenter_inactive_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='csccenter',
            name='last_paid_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='csccenter',
            name='next_payment_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
