# Generated by Django 5.0.6 on 2024-11-30 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csc_center', '0063_csccenter_last_paid_date_csccenter_next_payment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='csccenter',
            name='approved_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
