# Generated by Django 5.0.6 on 2024-11-30 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csc_center', '0064_csccenter_approved_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.AlterModelOptions(
            name='csccenter',
            options={'ordering': ['-created']},
        ),
    ]
