# Generated by Django 5.0.6 on 2025-01-07 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csc_center', '0065_delete_image_alter_csccenter_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpiredCscCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expired_date', models.DateField()),
                ('sent_expiry_email', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('csc_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csc_center.csccenter')),
            ],
            options={
                'db_table': 'expired_csc_centers',
                'ordering': ['-created'],
            },
        ),
    ]
