# Generated by Django 5.0.6 on 2025-01-23 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csc_center', '0069_alter_csccenter_contact_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csccenter',
            name='slug',
            field=models.SlugField(blank=True, max_length=500, null=True, unique=True),
        ),
    ]
