# Generated by Django 5.0.6 on 2024-07-01 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
