# Generated by Django 5.0.6 on 2024-12-13 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_emailverificationotp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailverificationotp',
            options={'ordering': ['updated']},
        ),
        migrations.AlterField(
            model_name='emailverificationotp',
            name='otp',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterModelTable(
            name='emailverificationotp',
            table='email_verification_otps',
        ),
    ]
