# Generated by Django 5.0.6 on 2024-12-16 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_alter_emailverificationotp_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email_verified',
        ),
        migrations.RemoveField(
            model_name='user',
            name='verification_token',
        ),
    ]
