# Generated by Django 5.0.6 on 2024-07-19 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Product Category', 'verbose_name_plural': 'Product Categories'},
        ),
    ]
