# Generated by Django 5.0.6 on 2024-07-19 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='stock',
            new_name='quantity',
        ),
    ]
