# Generated by Django 5.0.6 on 2024-08-07 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_productenquiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productenquiry',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, null=True),
        ),
    ]
