# Generated by Django 5.0.6 on 2024-08-13 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posters', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poster',
            old_name='image',
            new_name='poster',
        ),
    ]
