# Generated by Django 5.0.6 on 2024-08-13 15:44

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posters', '0002_rename_image_poster_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poster',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
