# Generated by Django 5.0.6 on 2024-08-17 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posters', '0004_customposter'),
    ]

    operations = [
        migrations.AddField(
            model_name='customposter',
            name='title',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
