# Generated by Django 5.0.6 on 2024-08-17 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posters', '0005_customposter_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='customposter',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
