# Generated by Django 5.0.6 on 2024-08-17 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posters', '0006_customposter_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='customposter',
            name='description',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
