# Generated by Django 5.0.6 on 2024-09-10 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posters', '0008_poster_state'),
        ('services', '0010_alter_serviceenquiry_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='poster',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.service'),
        ),
    ]
