# Generated by Django 5.0.6 on 2024-09-10 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posters', '0010_alter_poster_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poster',
            name='description',
        ),
    ]
