# Generated by Django 5.0.6 on 2024-09-10 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posters', '0012_remove_customposter_description_customposter_state'),
        ('services', '0010_alter_serviceenquiry_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='customposter',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='services.service'),
        ),
    ]
