# Generated by Django 5.0.6 on 2024-09-10 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posters', '0013_customposter_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customposter',
            name='state',
        ),
    ]
