# Generated by Django 5.0.6 on 2024-10-31 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csc_center', '0057_csccenter_csc_reg_no'),
        ('posters', '0014_remove_customposter_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='PosterFooter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='poster_footer/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('csc_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csc_center.csccenter')),
            ],
            options={
                'db_table': 'poster_footer',
                'ordering': ['created'],
            },
        ),
    ]
