# Generated by Django 5.0.6 on 2024-11-01 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posters', '0015_posterfooter'),
    ]

    operations = [
        migrations.AddField(
            model_name='posterfooter',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
