# Generated by Django 5.0.6 on 2024-11-16 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csc_center', '0057_csccenter_csc_reg_no'),
        ('posters', '0016_posterfooter_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poster',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='csc_center.state'),
        ),
        migrations.DeleteModel(
            name='CustomPoster',
        ),
    ]
