# Generated by Django 5.0.6 on 2024-12-12 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csc_center', '0065_delete_image_alter_csccenter_options'),
        ('posters', '0017_alter_poster_state_delete_customposter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poster',
            name='state',
        ),
        migrations.AddField(
            model_name='poster',
            name='state',
            field=models.ManyToManyField(to='csc_center.state'),
        ),
    ]
