# Generated by Django 5.0.6 on 2024-12-12 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posters', '0018_remove_poster_state_poster_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poster',
            old_name='state',
            new_name='states',
        ),
    ]
