# Generated by Django 5.0.6 on 2024-12-12 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posters', '0019_rename_state_poster_states'),
        ('products', '0012_remove_category_description'),
        ('services', '0011_alter_service_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='poster',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
        migrations.AlterField(
            model_name='poster',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.service'),
        ),
    ]
