# Generated by Django 5.0.6 on 2024-09-18 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_paymentrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentrequest',
            name='unique_token',
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='order_id',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
