# Generated by Django 5.0.6 on 2024-09-18 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csc_center', '0039_rename_csc_center_id_banner_csc_center'),
        ('payment', '0004_remove_paymentrequest_unique_token_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PaymentRequest',
            new_name='Payment',
        ),
    ]
