# Generated by Django 5.0.6 on 2024-09-20 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_payment_card_last4_payment_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
