# Generated by Django 5.0.6 on 2024-09-21 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='cgst',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='sgst',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
