# Generated by Django 5.0.6 on 2024-09-23 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0009_alter_price_cgst_alter_price_sgst'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='cgst',
        ),
        migrations.RemoveField(
            model_name='price',
            name='sgst',
        ),
        migrations.AddField(
            model_name='price',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='price',
            name='from_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='price',
            name='to_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
