# Generated by Django 5.0.6 on 2024-09-23 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0010_remove_price_cgst_remove_price_sgst_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='offer_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
