# Generated by Django 5.0.6 on 2024-10-17 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0011_price_offer_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaymentHistory',
        ),
    ]
