# Generated by Django 5.0.6 on 2024-10-25 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0012_delete_paymenthistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
