# Generated by Django 5.0.6 on 2024-08-30 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0002_enquiry_is_viewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='location',
            field=models.TextField(default=None, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enquiry',
            name='phone',
            field=models.TextField(default=9876543210, max_length=20),
            preserve_default=False,
        ),
    ]
