# Generated by Django 5.0.6 on 2024-08-30 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0003_enquiry_location_enquiry_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquiry',
            name='is_viewed',
        ),
    ]
