# Generated by Django 5.0.6 on 2024-08-30 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0004_remove_enquiry_is_viewed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquiry',
            name='subject',
        ),
    ]
